export const ScreenRegisterUser = 'ScreenRegisterUser';
export const ScreenRegisterConfirmPassword ='ScreenRegisterConfirmPassword';
export const ScreenRegisterFirstName ='ScreenRegisterFirstName';
export const ScreenRegisterLastName ='ScreenRegisterLastName';
export const ScreenRegisterNumber ='ScreenRegisterNumber';
export const ScreenMy ='ScreenMy';
export const ScreenDataPersonal ='ScreenDataPersonal';
export const ScreenRegisterPassword ='ScreenRegisterPassword';
export const ScreenHome ='ScreenHome';
export const ScreenDrawerIndex ='ScreenDrawerIndex'